version: '3.8'

services:
  django:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    volumes:
      - static:/srv/static
      - media:/srv/media
  nginx:
    image: nginx:1.25.3
    volumes:
      - static:/srv/static
      - media:/srv/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - django

volumes:
  static:
  media: